[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
rusqlite = "0.31.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
