[package]
name = "crab_rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
rocket = { version = "0.5.1", features = ["json", "uuid"] }
rocket_cors = "0.6.0"
diesel = { version = "2.1.0", features = ["postgres", "chrono", "uuid"] }
# Need to enable `chrono` feature to handle DateTime.
# https://docs.diesel.rs/master/diesel/sql_types/struct.Datetime.html
dotenvy = "0.15"
serde_json = "1.0.115"
chrono-tz = "0.5"
utoipa = { version = "4", features = ["rocket_extras"] }
rand = "*"
uuid = { version = "1.0", features = ["serde", "v4"] }


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
