[package]
name = "crab_rocket"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.9.0"
rocket = { version = "0.5.1", features = ["json", "uuid"] }
rocket_cors = "0.6.0"
diesel = { version = "2.1.0", features = ["postgres", "chrono", "uuid"] }
# Need to enable `chrono` feature to handle DateTime.
# https://docs.diesel.rs/master/diesel/sql_types/struct.Datetime.html
dotenvy = "0.15"
serde_json = "1.0.117"
utoipa = { version = "4", features = ["rocket_extras"] }
crab_rocket_utils = { version = "0.1.0" }
crab_rocket_task = { version = "0.1.0" }
crab_rocket_post = { version = "0.1.0" }
crab_rocket_follow = { version = "0.1.0" }
crab_rocket_role = { version = "0.1.0" }
crab_rocket_permission = { version = "0.1.0" }
crab_rocket_user = { version = "0.1.0" }
crab_rocket_employee = { version = "0.1.0" }
crab_rocket_info = { version = "0.1.0" }
crab_rocket_file = { version = "0.1.0" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
