version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello_rocket
    ports:
      - "15432:5432"

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/hello_rocket
    depends_on:
      - db
    ports:
      - "8000:8000"
