-- Your SQL goes here
CREATE TABLE IF NOT EXISTS order_table (
    order_id SERIAL PRIMARY KEY,
    customer_id INTEGER REFERENCES customer_table(customer_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    total_amount FLOAT,
    status VARCHAR(50) DEFAULT 'PENDING'
);
INSERT INTO order_table (customer_id, order_date, total_amount, status) VALUES
(1, CURRENT_TIMESTAMP, 1499.98, 'PENDING'),
(2, CURRENT_TIMESTAMP, 499.99, 'COMPLETED'),
(1, CURRENT_TIMESTAMP - INTERVAL '1 day', 299.99, 'SHIPPED'),
(2, CURRENT_TIMESTAMP - INTERVAL '2 days', 199.99, 'DELIVERED'),
(1, CURRENT_TIMESTAMP - INTERVAL '5 days', 1200.00, 'PENDING'),
(2, CURRENT_TIMESTAMP - INTERVAL '10 days', 800.00, 'RETURNED'),
(1, CURRENT_TIMESTAMP - INTERVAL '15 days', 450.00, 'COMPLETED'),
(2, CURRENT_TIMESTAMP - INTERVAL '20 days', 750.00, 'PENDING'),
(1, CURRENT_TIMESTAMP - INTERVAL '30 days', 999.99, 'COMPLETED'),
(2, CURRENT_TIMESTAMP - INTERVAL '40 days', 600.00, 'SHIPPED');
