[env]
PROJECT_NAME = "crab_rocket"

[tasks.run]
run = "cargo run"
alias = "r"

[tasks.clean]
depends = ['cleancache']
run = "cargo clean"      # runs as a shell command

[tasks.build]
description = 'Build the CLI'
run = "cargo build"
alias = 'b'                   # `mise run b`

[tasks.test]
description = 'Run automated tests'
run = [ # multiple commands are run in series
    'cargo test',
]

[tasks.ci] # only dependencies to be run
description = 'Run CI tasks'
depends = ['build', 'lint', 'test']
